### ISSUE TITLE
What Image To Use?

### ISSUE THREAD

**Issue by sherl0cks** [radanalyticsio/jupyter-notebook-py3.5#1]
This image or it's python 2.7 peer or https://github.com/radanalyticsio/base-notebook?

**Comment by elmiko** [comment]
depends what you are looking to do, this image will enable a python 3.5 interpreter for the notebook.

**Comment by sherl0cks** [comment]
i guess my issue is in the wrong place. See https://github.com/radanalyticsio/jupyter-notebook-py2.7/issues/1
