### ISSUE TITLE
Spark Session creation not possible

### ISSUE THREAD

**Issue by wolli2710** [radanalyticsio/jupyter-notebook-py3.5#5]
Hi, I deployed the project and now I wanted to run a simple example notebook but I already have troubles with the Spark Context. Are there any examples of notebooks that should work? or did I miss sth. in my container deployment?
![jupyter](https://user-images.githubusercontent.com/449792/51334998-4c04d800-1a81-11e9-922c-e302505f6f5e.PNG)

**Comment by elmiko** [comment]
hi @wolli2710 

i am not sure how up-to-date this repository is, if you would like to experiment with notebooks on OpenShift you might take a look at these links:

https://radanalytics.io/examples/var (this is a tutorial about launching and running a Jupyter notebook on OpenShift)
https://radanalytics.io/howdoi/launch-jupyter-notebook (this is a quickstart on how to run a Jupyter notebook in OpenShift)

**Comment by elmiko** [comment]
it looks like you may also have an error in how you obtain the SparkContext, you might need to set it up like this:

```
spark = SparkSession.builder.master("local[1]").getOrCreate()
sc = spark.sparkContext
```

**Comment by wolli2710** [comment]
@elmiko thanks for your help!

**Comment by wolli2710** [comment]
Just for completion... my problem was that at our companies openshift cluster we have resource limits per default. As I did not change them, I tried to run the image in a container with 128 mb (accidentially), which was obviously too less. I changed the resource limits to 1024 which seems to be the minimum needed for the use cases...

**Comment by willb** [comment]
Thanks @wolli2710 — this is good feedback and it would be useful to have a better experience in this case.

**Comment by elmiko** [comment]
excellent @wolli2710 , glad to hear you solved it =)
